// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtnPEMGws1a_ZKIuvdlJnic2eIMXlduU',
    appId: '1:473290862269:web:0f35bdef37b2bcfccf51d4',
    messagingSenderId: '473290862269',
    projectId: 'mynotes-flutterify',
    authDomain: 'mynotes-flutterify.firebaseapp.com',
    storageBucket: 'mynotes-flutterify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBd6dsVZ-4UHkJVElt_7MU3dTLbXGvuDc',
    appId: '1:473290862269:android:6b0bae6a54436b5ecf51d4',
    messagingSenderId: '473290862269',
    projectId: 'mynotes-flutterify',
    storageBucket: 'mynotes-flutterify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwFZyAx11nhNfPZ5j9xZzZPIcdgFeDXM',
    appId: '1:473290862269:ios:780418d38f5422a5cf51d4',
    messagingSenderId: '473290862269',
    projectId: 'mynotes-flutterify',
    storageBucket: 'mynotes-flutterify.appspot.com',
    iosClientId: '473290862269-jhirrun9e4jg3ahpln1l19s5f2s4p39g.apps.googleusercontent.com',
    iosBundleId: 'com.strawboy.fluttertut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwFZyAx11nhNfPZ5j9xZzZPIcdgFeDXM',
    appId: '1:473290862269:ios:780418d38f5422a5cf51d4',
    messagingSenderId: '473290862269',
    projectId: 'mynotes-flutterify',
    storageBucket: 'mynotes-flutterify.appspot.com',
    iosClientId: '473290862269-jhirrun9e4jg3ahpln1l19s5f2s4p39g.apps.googleusercontent.com',
    iosBundleId: 'com.strawboy.fluttertut',
  );
}
